package v1alpha1

import (
	rbacv1 "k8s.io/api/rbac/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RBACSessionSpec is empty — RBACSession resources are generated by the operator.
// Users should never write to this field.
type RBACSessionSpec struct{}

// RBACSessionStatus is the full observed RBAC state of the cluster,
// as managed by rbac-therapist.
//
// This is the case notes: a point-in-time snapshot of who has what access,
// through which policies, and why. It is the primary input for `rbact explain`,
// `rbact audit`, and `rbact graph`.
type RBACSessionStatus struct {
	// GeneratedAt is the time this snapshot was generated.
	GeneratedAt *metav1.Time `json:"generatedAt,omitempty"`

	// SubjectAccess is the full index of access, keyed by subject.
	// Each entry describes all the access a given subject has, and the
	// complete policy chain that granted it.
	//
	// +optional
	SubjectAccess []SubjectAccessEntry `json:"subjectAccess,omitempty"`

	// NamespaceAccess is the access index keyed by namespace.
	// Each entry lists all subjects with access to that namespace and their roles.
	//
	// +optional
	NamespaceAccess []NamespaceAccessEntry `json:"namespaceAccess,omitempty"`

	// PolicySummaries provides a high-level summary of each active AccessPolicy.
	//
	// +optional
	PolicySummaries []PolicySummary `json:"policySummaries,omitempty"`

	// Warnings are non-fatal issues detected during snapshot generation.
	// Examples: expired policies still in place, role references that don't exist.
	//
	// +optional
	Warnings []string `json:"warnings,omitempty"`
}

// SubjectAccessEntry describes all access a single subject has across the cluster.
type SubjectAccessEntry struct {
	// Subject is the Kubernetes subject (User, Group, ServiceAccount).
	Subject rbacv1.Subject `json:"subject"`

	// Teams lists the Team CRD names this subject belongs to.
	// +optional
	Teams []string `json:"teams,omitempty"`

	// Access lists all role grants this subject has, with provenance.
	// +optional
	Access []AccessGrant `json:"access,omitempty"`
}

// AccessGrant is a single role grant to a subject, with full provenance.
type AccessGrant struct {
	// Role is the ClusterRole or Role name.
	Role string `json:"role"`

	// RoleKind is ClusterRole or Role.
	RoleKind string `json:"roleKind"`

	// Namespace is the namespace of the RoleBinding. Empty for ClusterRoleBindings.
	// +optional
	Namespace string `json:"namespace,omitempty"`

	// ClusterWide is true if this grant is via a ClusterRoleBinding.
	// +optional
	ClusterWide bool `json:"clusterWide,omitempty"`

	// Via describes the policy chain that produced this grant.
	Via AccessGrantProvenance `json:"via"`
}

// AccessGrantProvenance describes how an access grant was produced.
type AccessGrantProvenance struct {
	// PolicyRef is the AccessPolicy or RBACBinding that created this grant.
	PolicyRef string `json:"policyRef"`

	// PolicyKind is AccessPolicy or RBACBinding.
	PolicyKind string `json:"policyKind"`

	// TeamRef is the Team that linked this subject to the policy, if applicable.
	// +optional
	TeamRef string `json:"teamRef,omitempty"`

	// MatchReason describes why this namespace was selected for the binding.
	// Examples:
	//   "static name list"
	//   "label selector: tier=platform"
	//   "matchTeamTags: team tags {tier=platform,env=production} match namespace labels"
	//
	// +optional
	MatchReason string `json:"matchReason,omitempty"`

	// Rationale is the rationale text from the source policy.
	// Surfaced here so that `rbact explain` can show justification inline.
	Rationale string `json:"rationale"`
}

// NamespaceAccessEntry describes all access within a single namespace.
type NamespaceAccessEntry struct {
	// Namespace name.
	Namespace string `json:"namespace"`

	// Labels are the namespace labels at snapshot time.
	// +optional
	Labels map[string]string `json:"labels,omitempty"`

	// Grants lists all access grants for this namespace.
	// +optional
	Grants []NamespaceAccessGrant `json:"grants,omitempty"`
}

// NamespaceAccessGrant is a single access grant entry in a namespace view.
type NamespaceAccessGrant struct {
	// Subject is the Kubernetes subject.
	Subject rbacv1.Subject `json:"subject"`

	// Role is the ClusterRole or Role name.
	Role string `json:"role"`

	// PolicyRef is the AccessPolicy or RBACBinding that created this grant.
	PolicyRef string `json:"policyRef"`
}

// PolicySummary is a high-level summary of an AccessPolicy in the snapshot.
type PolicySummary struct {
	// Name of the AccessPolicy.
	Name string `json:"name"`

	// Rationale from the policy.
	Rationale string `json:"rationale"`

	// EffectiveSubjectCount is the number of resolved subjects (after expanding TeamRefs).
	EffectiveSubjectCount int `json:"effectiveSubjectCount"`

	// ManagedBindingCount is the total number of RoleBindings + ClusterRoleBindings.
	ManagedBindingCount int `json:"managedBindingCount"`

	// Paused indicates the policy is currently suspended.
	// +optional
	Paused bool `json:"paused,omitempty"`

	// ExpiresAt is the policy expiry, if set.
	// +optional
	ExpiresAt *metav1.Time `json:"expiresAt,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,shortName=session,categories=rbac-therapist
// +kubebuilder:printcolumn:name="Generated",type="date",JSONPath=".status.generatedAt"
// +kubebuilder:printcolumn:name="Subjects",type="integer",JSONPath=".status.subjectAccess",description="Number of tracked subjects"
// +kubebuilder:printcolumn:name="Warnings",type="integer",JSONPath=".status.warnings",description="Number of warnings"

// RBACSession is the case notes: a point-in-time snapshot of all RBAC access
// managed by rbac-therapist. It is generated and updated by the operator.
//
// Users should never create or modify RBACSession resources.
// Use `rbact snapshot` to force a refresh.
//
// The RBACSession feeds:
//   - `rbact explain` — who has access to a namespace and why
//   - `rbact audit`   — LLM-powered full cluster audit report
//   - `rbact graph`   — Mermaid dependency graph
//   - `rbact who-can` — "who can do X on Y?" queries
//
// Therapy note: This is the complete case file. Everything that happened
// in this cluster's RBAC history, organized for review.
type RBACSession struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec RBACSessionSpec `json:"spec,omitempty"`

	// +optional
	Status RBACSessionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RBACSessionList contains a list of RBACSession.
type RBACSessionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RBACSession `json:"items"`
}

func init() {
	SchemeBuilder.Register(&RBACSession{}, &RBACSessionList{})
}
